---
title: "Github Configuration"
description:  "Github Configuration"
author: "RPythonStudyGroup feat. ChatGPT"
date: "2024-12-17"
date-modified: "2024-12-18"
categories: [Github, Configuration]
---

### 매뉴얼
- Github documentation <https://docs.github.com/en>을 참조를 추천합니다.

#### subscription
- 위 Github documentation에 따르면 Github 특정활동에 대한 지속적인 업데이트를 받는 것을 notification(알림)을 subscribe(구독)한다고 표현하고 있습니다.
- Subscribe option은 아래와 같습니다.
    - A conversation in a specific issue, pull request, or gist
    - All activity in a repository
    - CI activity, such as the status of workflows in repositories set up with GitHub Actions
    - Repository issues, pull requests, releases, security alerts, or discussions (if enabled)
- 다른 맥락으로 저장소에 대한 watch 개념이 있으며, 자동감시에 해당하며 설정을 통해 해제할 수 있습니다.
- 구체적인 사항은 아래의 제한적인 경우에 대해 우선적으로 설명드리겠습니다.

#### Configuration notification
- 알림을 수신하는 방식은 notifications inbox of web interface, notifications inbox of mobile app, email로 지정할 수 있습니다.
- 알림수신방식 지정은 notifications inbox 우하단의 Management notifications에서 할 수 있습니다.
    - Watched repository에서는 감시중인 저장소 목록을 확인할 수 있고 일관 변경할 수 있습니다.
    - Unwatch 를 watching으로 변경할려면 개별저장소에서 해야 합니다.